apiVersion: batch/v1
kind: Job
metadata:
  name: devops-userspace-job
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: devops-userspace-container
        image: alpine:edge
        imagePullPolicy: Always
        workingDir: /root
        command: ['sh']
        args:
          - '-c'
          - >-
            apk add curl ; curl -fSL https://gitlab.com/vmath3us/devops-userspace/-/raw/main/sh-provisioning.sh | sh ; sleep infinity
      restartPolicy: OnFailure
